title: Learning Hub
relative_links:
  enabled:     true
  collections: true
remote_theme:  "kathuriaas/just-the-docs"
aux_links:
  "Visit the repo on GitHub": "https//github.com/kathuriaas/kathuriaas.github.io"
aux_links_new_tab: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/kathuriaas/kathuriaas.github.io" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
