title: Code Examples
relative_links:
  enabled:     true
  collections: true
remote_theme:  "kathuriaas/just-the-docs"
aux_links:
  "Visit the repo on GitHub":
    - "//github.com/kathuriaas/kathuriaas.github.io"
aux_links_new_tab: false
